sudo: required
dist: trusty
language: node_js
node_js:
  - '6.9.1'
  - '7.10.0'
addons:
  apt:
    sources:
      - google-chrome
      - ubuntu-toolchain-r-test
    packages:
      - google-chrome-stable
      - g++-4.8
  firefox: 'latest-esr'
cache:
  directories:
  - node_modules
env:
  matrix:
    - EMBER_TRY_SCENARIO=ember-2-3
    - EMBER_TRY_SCENARIO=ember-2-8
    - EMBER_TRY_SCENARIO=default
    - EMBER_TRY_SCENARIO=ember-release
  global:
    - CXX=g++-4.8
    - secure: UAeyuAKSROuXqFhNeMMMKhSTwyO7J1o/dyT7p/nVVlxagujCD2A4ggzREg+HBCWDurDqdmN5tVYTC+crVVgjmX9lIpukDGAomXR5wln8niSlu4H0rxqBdbjuCKFbS8EPKy56c/n50TNMjMCkCejAU8sdZLbJT8OMHpLMdl+WkyCGEzBgNiTbxUFu5AkuVAhhS0xBChiBh6uCLXqOku9B2UDIs9U9qYV99B0HLOeksZS/errOtVpaJr+qQOP0tm+cbtUxeI+Ub+uEnnuoKjbEtJwnzaToZPA2i9X+Xe9WR0sIXFmS/vF1syVYdvZE2z/fCCydjwczM93Td/Oq9KluFikwX+y807MmgjFiv1rSeBRLob8wKQBlNoEc+NydDsRdQjsFjOQWG0yc/C78Xqi7PHipZw/Wf5GzOgxmxqjOvM2s16VBI9UJPcMme7FykDeHwoROi4xCGvjFLyxJ3UjsthwY+uRS1YVmGIlqMUJEdSUquAeVevRaEaPmH4n6qdXsTjMw+75UPfw4SgBZuO0DFnC8Tgr4UZY6IkL7NQxWenZZje1pkjTkBHLy7SitNjugEYqukVf5SGUyC2mtMbbBDOlZBQML9/s7jbmGFENbAc2+EtvVq2Hu+u+DciN9IRSwZtmI06p8d1ifCwoU1NU7RCdchu22n0D8/EG6aDuOwDI=
matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-release
before_install:
  - npm config set spin false
  - npm install -g coveralls pr-bumper@^1.0.0
  - $(npm root -g)/pr-bumper/.travis/maybe-check-scope.sh
install:
  - $(npm root -g)/pr-bumper/.travis/maybe-install.sh
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - $(npm root -g)/pr-bumper/.travis/maybe-test.sh
  - .travis/maybe-bump-version.sh
after_success:
  - .travis/maybe-publish-coverage.sh
  - .travis/maybe-publish-gh-pages.sh
deploy:
  provider: npm
  email: npm.ciena@gmail.com
  skip_cleanup: true
  api_key:
    secure: kOUhZ/JbccEhA7JKlxaW8EhyDw6zIXzNgT13861tfz3EsWsGk4OKxGvJI9metrvfFSX2gbghIwYsq4s3/5EecLU44Cm1a2SVL92qZvFYqfHsdtStCiSVPV9BewDjhRTs4GIctRowln+SP3S9p2/DBJymR2tupjfLS5WaeCmJu9YU3qtu7cVHWoqJuX1udjlzaG95VdQ7YlWKubDGAF8gRtrIG4QkYTNSGY1ivVKOn59S/IW+rHudA0kF6doGYk3vfMN3TTzoxuiIi1eIZ8211Q8uedJqku0rj4i/j5GQIzoeDfW21iD8bl7wHFnvKFmssP915jnD5X+bRvBiJ/Ore0d+PrjrIhZzEPilN1eftfg8Cu3EzBOBnf3bV80wD1p8bXNZj2Ip3gycOFwo2YnRr2xyR1R7wDt+J6XVNyJNVuD+u1LWk+Uxd1krGJtitB1mz95gNKTQveQ6tK/M3K4zv7JSoz9BP3wbXs0bpTdq8ETPGSBpTUgVTSetjJ3nvTkuctOtOeHOZjxP9XN4Gzu1c3sB3zSOX5squwVmIvDfSO6huF/6ESJxzLheQzveW1COQSv9S/Pt5ZO/jrXyBlrX4DhlRl2GbF/mxiNVB4zlCrvzeYIqfOHjPQRRV4vsFp3VbiZ4LI/lI4m7RWuHxmOZclg3BjNwZTsunGiZWdXIyq8=
  on:
    all_branches: true
    condition: "$EMBER_TRY_SCENARIO = 'default'"
    node: '6.9.1'
    tags: true
notifications:
  slack:
    secure: AeQP9RKrNCWJODL8xHlkvKISD1+rWU1h/hFdPoQkJWjXOV8/0wwrEPFJ8TMc7lkBkWUp22aqLJuFIhw/t/au09zk0QJbVIZafWQB8z6nrgc6ceZUAM648wRTgHVYe3UapvnoQ2nwl4/KuN9v1sTRdIpKag21LnPvNqhHdCHfNdfrX0/5Ld2Ui3pyVMBXmx+sl5/p/fqxK87ZmGNFvoXy4T1s/DW30LpdL4FFvfOTJpm+1TfMJvkjVnt3MOp7pzneNDXzCatMhlUHYZuHXYhQezTy5g1XyG6L7YgyaXuMrSK+J/wu0nyX0mEx9FQMJledW5M8XPdQVcxyFJuf9sUvb2wD5mNVTl6TbktiLtP0pz9rG5qVRGjgXhl/BXrC42KYleS5C47ky5mruSC+QY3yAYwIZntTHV7R9E9Q95bME8TU0h25ENKWxh1aftd3CXDJvotzUEE4CCoyBZIFqv4TJGQCEkhiGMDDGmKcTpgEJpD2YuLmXWFWzCs3tZVIgDWnkNh+4DP5PRxfpDRjew5TObWhUL4zMJLVLkytuVMa7ph44/6Mol4nrF4b/kaFoAoxDr91GchqCTHs9fm8mrCFZCOBqv4X6i/rmcEZUkJ8Fq2siXmi5w/+yjCnHHWDrOh4tV8e8QUsqLnRdKkC0wWkF9Dug4DaI5PdDtOWcObU/Mo=
